#pragma once

#include <string>

enum class Language {
    Spanish,
    English
};

enum class TextId {
    MenuNewDream,
    MenuContinueExploring,
    MenuControls,
    MenuCredits,
    MenuLanguage,
    MenuExit,
    LoadingResources,
    ChooseHowToStart,
    SkipStory,
    ViewStory,
    ControlsTitle,
    ControlsWalkStrafe,
    ControlsLookAround,
    ControlsJump,
    CreditsBackHint,
    ControlsBackHint,
    VersionAlpha,
    CreditsMadeBy,
    CreditsTitle,
    CreditsTeam,
    CreditsProgram,
    CreditsUniversity,
    CreditsDegree,
    CreditsCourseProject,
    CreditsThanks,
    HousePreparingScene,
    HouseFailedLoad,
    HouseFailedError,
    PauseTitle,
    PauseResume,
    PauseReturnMenu,
    VN_S0_0,
    VN_S0_1,
    VN_S0_2,
    VN_S0_3,
    VN_S0_4,
    VN_S0_5,
    VN_S0_6,
    VN_S0_7,
    VN_S0_8,
    VN_S0_9,
    VN_S0_10,
    VN_S0_11,
    VN_S0_12,
    VN_S1_0,
    VN_S1_1,
    VN_S1_2,
    VN_S1_3,
    VN_S1_4,
    VN_S1_5,
    VN_S2_0,
    VN_S2_1,
    VN_S2_2,
    VN_S2_3,
    VN_S2_4,
    VN_S2_5,
    VN_S2_6,
    VN_S2_7,
    VN_S2_8,
    VN_S2_9,
    VN_S2_10,
    VN_S2_11,
    VN_S3_0,
    VN_S3_1,
    VN_S3_2,
    VN_S3_3,
    VN_S3_4,
    VN_S3_5,
    VN_S3_6,
    VN_S3_7,
    VN_S3_8,
    VN_S3_9,
    VN_S3_10,
    VN_S3_11,
    VN_S4_0,
    VN_S4_1,
    VN_S4_2,
    VN_S4_3,
    VN_S4_4,
    VN_S4_5,
    VN_S4_6,
    VN_S4_7,
    VN_S4_8,
    VN_S4_9,
    VN_S4_10,
    VN_S5_0,
    VN_S5_1,
    VN_S5_2,
    VN_S5_3,
    VN_S5_4,
    VN_S5_5,
    VN_S5_6,
    VN_S6_0,
    VN_S6_1,
    VN_S6_2,

    CoinDialogueTitle,
    CoinDialoguePage1,
    CoinDialoguePage2,
    CoinDialoguePage3,
    CoinCounter,
    CoinApproachMsg,
    MinigameWin,
    MinigameLose,
    CoinAllCollected,
    BedroomExitMsg,
    BedroomExitLocked,
    MinigameTimingTitle,
    MinigameTimingInstruction,
    MinigameAttempts,
    MinigameMemoryTitle,
    MinigameMemoryPairs,
    MinigamePatternTitle,
    MinigamePatternObserve,
    MinigamePatternRepeat,
    MinigamePatternProgress,
    MinigameMatchFound,
    MinigameSpeedLabel,
    MinigameSequenceShow,
    MinigameSequenceRepeat,
    CoinDialogueHint,
    CoinDialogueStart,
    MinigamePerfect,
    MinigameCombo,
    MinigameLevel,
    MinigamePreview,
    MinigameGameOver,
    MinigameRetry,
    MinigameQuickTapTitle,
    MinigameQuickTapInstruction,
    MinigameQuickTapHits,
    MinigameColorMatchTitle,
    MinigameColorMatchInstruction,
    MinigameColorMatchRound,
    MinigameColorMatchScore,
    MinigameSequenceTitle,
    MinigameSequenceInstruction,
    MinigameSequenceObserve,
    MinigameTutorialStart,
    MinigameTutorialQuickTap,
    MinigameTutorialColorMatch,
    MinigameTutorialSequence,
    MinigameExitHint,
    MinigameFindColor,
    MinigameYourTurn,
    MinigameTargets,
    MinigameTapToStart,
    MinigameCountdownGo
};

namespace Localization {
Language current();
void set(Language lang);
void toggle();
Language load(const std::string& filePath);
void save(const std::string& filePath);
std::string t(TextId id);
std::string languageLabel(Language lang);
}
